name: Chall Intro

on:
  issue_comment:
    types: [created, edited]

permissions:
  issues: write
  contents: write

jobs:
  access_secret_flag:
    runs-on: ubuntu-latest
    steps:
      - name: Set USERINPUT from issue body
        env:
          issue_comment_body: ${{ github.event.comment.body }}
        run: |
          echo "Welcome Louis. The secret flag is ${{ secrets.FLAG }}" | base64 | base64